input {
  udp {
    port => 5959
  }
}

filter { 
  # Questo filtro decodifica il campo 'message' come JSON
  json {
    source => "message"
    target => ""      # Unisce i campi nell'oggetto principale
  }

  mutate { 
    remove_field => [ "event", "tags", "type","path","event.original" ] 
  
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "python-logs"
  }
  stdout { codec => rubydebug }
}